### ISSUE TITLE
推奨ブラウザがIE

### ISSUE THREAD

**Issue by Lucky3028** [unchama/info-jpmcs.seichi.click#3]
少し前から思ってたんですが、どうなんですか？

**Comment by unchama** [comment]
ぶっちゃけIE使って投票したことないけどJPMCSまたは整地鯖の障害以外でもらえなかったことはない

**Comment by Lucky3028** [comment]
そんならそのままでもいいんすかね...

**Comment by unchama** [comment]
いえ、IEとSafari以外でも差し支え無さそうなので、記載を消してしまってもよさそうという見解です！

**Comment by Lucky3028** [comment]
なるほど、じゃあそうします？

**Comment by unchama** [comment]
はい、良いと思います

**Comment by Lucky3028** [comment]
あ、じゃあやりますはい
